[template]
src  = "Caddyfile.tmpl"
dest = "/etc/caddy/Caddyfile"
keys = [
    "/caddy/fqdn",
    "/caddy/auth/url",
    "/caddy/client/id",
    "/caddy/client/secret",
    "/caddy/token/name",
    "/caddy/token/secret",
    "/proxy"
]